AWSTemplateFormatVersion: '2010-09-09'
Description: HPC-FSx-Lustre

Parameters:
  PrivateSubnet:
    Description: The ID of your private subnet.
    Type: String
    AllowedPattern: ^(subnet-[0-9a-z]+)$
  SecurityGroup:
    Description: The ID of the SecurityGroup you want to attach.
    Type: String
    AllowedPattern: ^(sg-[0-9a-z]+)$

Resources:

  FSx:
    DeletionPolicy: Retain
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: LUSTRE
      StorageCapacity: 1200
      StorageType: SSD
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref SecurityGroup
      LustreConfiguration:
        WeeklyMaintenanceStartTime: "4:00:00"
        DeploymentType: PERSISTENT_2
        PerUnitStorageThroughput: 1000
        DataCompressionType: LZ4
      FileSystemTypeVersion: "2.12"